---
title: "Estimate tumor purity by the estimate package"
output: html_notebook
---

```{r}
library(estimate)
OvarianCancerExpr <- system.file('extdata', 'sample_input.txt', package = 'estimate')
filterCommonGenes(input.f = OvarianCancerExpr, output.f = "OV_10412.genes.gct", id = 'GeneSymbol')
estimateScore('OV_10412.genes.gct', 'OV_estimate_score.gct', platform = 'affymetrix') -> d

plotPurity(scores = 'OV_estimate_score.gct', samples = 's516', platform = 'affymetrix')
```
```{r}
ptm <- proc.time()
filterCommonGenes(input.f = OvarianCancerExpr, output.f = 'OV_10412.genes.gct', id = 'GeneSymbol')
proc.time() - ptm
```


## use mixtools

```{r}
library(mixtools)
data("faithful")
attach(faithful)
hist(waiting, main = 'Time between Old Faithful eruptions', xlab = 'Minutes', ylab = '', cex.main = 1.5, cex.lab = 1.5, cex.axis = 1.4)

mixmdl <- normalmixEM(waiting)
plot(mixmdl, which = 2)

```
```{r}
library(data.table)
library(ggplot2)

head(faithful)

ggplot(faithful, aes(waiting)) + geom_density()



```

```{r}
h <- density(faithful$waiting)$x[which.max(density(faithful$waiting)$y)]

ggplot(faithful, aes(waiting)) + geom_density() + geom_vline(xintercept = h)
```

```{r}
i <- density(faithful$waiting)$x[which.max(density(faithful$waiting)$y[density(faithful$waiting)$x < 65])]
ggplot(faithful, aes(waiting)) + geom_density() + geom_vline(xintercept = i)

```
```{r}
densityfaithfulY <- density(faithful$waiting)$y
densityfaithfulX <- density(faithful$waiting)$x
mindensityY <- min(densityfaithfulY[densityfaithfulX < h & densityfaithfulX > i])
mindensityY
j <- densityfaithfulX[which(densityfaithfulY == mindensityY)]

ggplot(faithful, aes(waiting)) + geom_density() + geom_vline(xintercept = i) + geom_vline(xintercept = j) + geom_vline(xintercept = h)
```

